#version 460 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

#define MAX_LIGHTS_PER_CLUSTER 200

uniform uint gridDimX;
uniform uint gridDimY;
uniform uint gridDimZ;
uniform uint num_Lights;

//uniform mat4 view_c;

/*
layout (std140, binding = 0) uniform matrices_cam
{
 mat4 view_c;
 mat4 projection_c;
};
*/

struct cluster_D
{
 vec4 minPoint;
 vec4 maxPoint;
};

layout (std430, binding = 4) readonly buffer clustersBuffer
{
 cluster_D clusters[];
};

/////////////

struct Light
{
 vec4 lightPos_radius; // 0-12  ---> .w == radius
 vec4 Color_And_Intensity; // 76-80
 vec4 Direction;
 int lightState; // state of the light
 int light_Type; /// 0 == DIRECTIONAL LIGHT /// 1 == POINT LIGHT /// 2 == SPOT LIGHT
 float cutOff;
 float outerCutOff;
};

layout (std430, binding = 5) readonly buffer Lights_D
{
 Light Lights_Array[];

};

struct Cluster_LightsData
{
  uint offset;
  uint count;
};

layout (std430, binding = 6) writeonly buffer light_GridBuffer
{
  Cluster_LightsData cluster_Lights[];
};

layout (std430, binding = 7) writeonly buffer global_ID_LightBuffer
{
  uint global_ID_lights[];
};

layout (std430, binding = 8) buffer globalCounter_Atomic
{
 uint nextSlot;
};


bool intersect_Light(vec4 lightPos_radius, vec3 minPt_AABB, vec3 maxPt_AABB)
{
   //vec4 lightPos_viewSpace = view_c * vec4(lightPos_radius.xyz, 1.0);

   vec3 closest_Pt_AABB = clamp(lightPos_radius.xyz, minPt_AABB, maxPt_AABB);

   vec3 dist_pt_Light = lightPos_radius.xyz - closest_Pt_AABB;

   float dist_AABB_Light = dot(dist_pt_Light, dist_pt_Light);
   float dist_radiusLight = lightPos_radius.w * lightPos_radius.w;

   return dist_AABB_Light <= dist_radiusLight;
}


void main()
{
  uint tileX = gl_GlobalInvocationID.x;
  uint tileY = gl_GlobalInvocationID.y;
  uint sliceZ = gl_GlobalInvocationID.z;

  uint clusterIndex = tileX + (tileY * gridDimX) + (sliceZ * gridDimX * gridDimY);

      //float dist_pts = distance(clusters[tileIndex].minPoint, clusters[tileIndex].maxPoint);
        vec3 minPos_AABB = clusters[clusterIndex].minPoint.xyz;
        vec3 maxPos_AABB = clusters[clusterIndex].maxPoint.xyz;

        uint lights_MaxVisible[MAX_LIGHTS_PER_CLUSTER];
        uint light_count = 0;

        for(uint i = 0; i < num_Lights; i++)
        {
          Light light_current = Lights_Array[i];

            if(light_current.light_Type == 1)
            {
                vec4 right_light = light_current.lightPos_radius;
                //right_light.w += 0.05;

                bool light_intersect_AABB = intersect_Light(right_light, minPos_AABB, maxPos_AABB);

                if (light_intersect_AABB == true)
                {
                    if (light_count < MAX_LIGHTS_PER_CLUSTER)
                    {
                        lights_MaxVisible[light_count] = i;
                        light_count++;
                    }
                }
            }
        }

        uint offset = atomicAdd(nextSlot, light_count);

        cluster_Lights[clusterIndex].offset = offset;
        cluster_Lights[clusterIndex].count = light_count;

    for(uint i = 0; i < light_count; i++)
    {
        global_ID_lights[offset + i] = lights_MaxVisible[i];
    }

}








